import { nowDate } from "./cnab240.js";

export const sampleEmpresa = {
  codigoBanco: "237",
  tipoInscricao: "2",
  cnpj: "11.222.333/0001-81",
  convenio: "123456",
  agencia: "03290",
  dvAgencia: "5",
  conta: "000000012345",
  dvConta: "5",
  dvAgConta: "",
  nome: "ACME TECNOLOGIA LTDA",
  nomeBanco: "BRADESCO",
  logradouro: "AV PAULISTA",
  numero: "1000",
  complemento: "ANDAR 15",
  cidade: "SAO PAULO",
  cep: "01310-100",
  estado: "SP",
  dataGeracao: nowDate(),
  horaGeracao: "",
  nsa: "1",
  versaoLayoutArquivo: "089",
};

export const sampleLote = {
  tipoServico: "20",
  formaLancamento: "41",
  indicativoFormaPagamento: "01",
  mensagem: "PAGAMENTO FORNECEDORES ABR/2026",
  versaoLayoutLote: "045",
};

export const samplePagamentos = [
  {
    id: Date.now(),
    bancoFavorecido: "341",
    agenciaFavorecido: "04567",
    dvAgenciaFav: "8",
    contaFavorecido: "000000789012",
    dvContaFav: "3",
    dvAgContaFav: "",
    nomeFavorecido: "JOAO DA SILVA SANTOS",
    cpfCnpjFavorecido: "529.982.247-25",
    tipoInscricaoFav: "1",
    formaIniciacao: "   ",
    valor: "1500.00",
    dataPagamento: nowDate(),
    seuNumero: "REF-00001",
    tipoMoeda: "BRL",
    camara: "018",
    tipoMovimento: "0",
    codInstrucao: "00",
    codFinalidadeTED: "00005",
    codFinalidadeDoc: "  ",
    codFinalidadeComp: "CC",
    aviso: "0",
    info2: "",
    nossoNumero: "",
    dataRealPagamento: "",
    valorRealPagamento: "",
    quantidadeMoeda: "",
    ugSiape: "",
    ispb: "",
    // Segmento B - Endereco
    logradouroFav: "RUA DAS FLORES",
    numeroFav: "123",
    complementoFav: "SALA 10",
    bairroFav: "CENTRO",
    cidadeFav: "SAO PAULO",
    cepFav: "01001-000",
    estadoFav: "SP",
    // Segmento B - Valores
    dataVencimento: "",
    valorDocumento: "",
    valorAbatimento: "",
    valorDesconto: "",
    valorMora: "",
    valorMulta: "",
    codDocFavorecido: "",
    avisoFav: "0",
  },
  {
    id: Date.now() + 1,
    bancoFavorecido: "033",
    agenciaFavorecido: "01234",
    dvAgenciaFav: "0",
    contaFavorecido: "000000456789",
    dvContaFav: "1",
    dvAgContaFav: "",
    nomeFavorecido: "EMPRESA BETA SERVICOS LTDA",
    cpfCnpjFavorecido: "33.000.167/0001-01",
    tipoInscricaoFav: "2",
    formaIniciacao: "   ",
    valor: "8750.50",
    dataPagamento: nowDate(),
    seuNumero: "REF-00002",
    tipoMoeda: "BRL",
    camara: "018",
    tipoMovimento: "0",
    codInstrucao: "00",
    codFinalidadeTED: "00005",
    codFinalidadeDoc: "  ",
    codFinalidadeComp: "CC",
    aviso: "0",
    info2: "",
    nossoNumero: "",
    dataRealPagamento: "",
    valorRealPagamento: "",
    quantidadeMoeda: "",
    ugSiape: "",
    ispb: "",
    // Segmento B - Endereco
    logradouroFav: "AV BRASIL",
    numeroFav: "500",
    complementoFav: "",
    bairroFav: "JARDIM AMERICA",
    cidadeFav: "RIO DE JANEIRO",
    cepFav: "20040-020",
    estadoFav: "RJ",
    // Segmento B - Valores
    dataVencimento: "",
    valorDocumento: "",
    valorAbatimento: "",
    valorDesconto: "",
    valorMora: "",
    valorMulta: "",
    codDocFavorecido: "NF 4521",
    avisoFav: "0",
  },
];
