import { nowDate } from "./cnab240.js";
import { defaultPagamento } from "./constants.js";

export const sampleEmpresa = {
  codigoBanco: "237",
  tipoInscricao: "2",
  cnpj: "11.222.333/0001-81",
  convenio: "123456",
  agencia: "03290",
  dvAgencia: "5",
  conta: "000000012345",
  dvConta: "5",
  dvAgConta: "",
  nome: "ACME TECNOLOGIA LTDA",
  nomeBanco: "BRADESCO",
  logradouro: "AV PAULISTA",
  numero: "1000",
  complemento: "ANDAR 15",
  cidade: "SAO PAULO",
  cep: "01310-100",
  estado: "SP",
  dataGeracao: nowDate(),
  horaGeracao: "",
  nsa: "1",
  versaoLayoutArquivo: "089",
};

// ─── TED ──────────────────────────────────────────────
export const sampleLoteTED = {
  tipoServico: "20",
  formaLancamento: "41",
  indicativoFormaPagamento: "01",
  mensagem: "PAGAMENTO FORNECEDORES ABR/2026",
  versaoLayoutLote: "045",
};

export const samplePagamentosTED = [
  {
    ...defaultPagamento,
    bancoFavorecido: "341",
    agenciaFavorecido: "04567",
    dvAgenciaFav: "8",
    contaFavorecido: "000000789012",
    dvContaFav: "3",
    nomeFavorecido: "JOAO DA SILVA SANTOS",
    cpfCnpjFavorecido: "529.982.247-25",
    tipoInscricaoFav: "1",
    valor: "1500.00",
    dataPagamento: nowDate(),
    seuNumero: "REF-00001",
    camara: "018",
    codFinalidadeTED: "00005",
    codFinalidadeComp: "CC",
    logradouroFav: "RUA DAS FLORES",
    numeroFav: "123",
    complementoFav: "SALA 10",
    bairroFav: "CENTRO",
    cidadeFav: "SAO PAULO",
    cepFav: "01001-000",
    estadoFav: "SP",
  },
  {
    ...defaultPagamento,
    bancoFavorecido: "033",
    agenciaFavorecido: "01234",
    dvAgenciaFav: "0",
    contaFavorecido: "000000456789",
    dvContaFav: "1",
    nomeFavorecido: "EMPRESA BETA SERVICOS LTDA",
    cpfCnpjFavorecido: "33.000.167/0001-01",
    tipoInscricaoFav: "2",
    valor: "8750.50",
    dataPagamento: nowDate(),
    seuNumero: "REF-00002",
    camara: "018",
    codFinalidadeTED: "00005",
    codFinalidadeComp: "CC",
    logradouroFav: "AV BRASIL",
    numeroFav: "500",
    bairroFav: "JARDIM AMERICA",
    cidadeFav: "RIO DE JANEIRO",
    cepFav: "20040-020",
    estadoFav: "RJ",
    codDocFavorecido: "NF 4521",
  },
];

// ─── PIX ──────────────────────────────────────────────
export const sampleLotePIX = {
  tipoServico: "20",
  formaLancamento: "45",
  indicativoFormaPagamento: "01",
  mensagem: "PAGAMENTO PIX FORNECEDORES ABR/2026",
  versaoLayoutLote: "045",
};

export const samplePagamentosPIX = [
  {
    ...defaultPagamento,
    bancoFavorecido: "237",
    agenciaFavorecido: "03290",
    dvAgenciaFav: "5",
    contaFavorecido: "000000012345",
    dvContaFav: "5",
    nomeFavorecido: "JOAO DA SILVA SANTOS",
    cpfCnpjFavorecido: "529.982.247-25",
    tipoInscricaoFav: "1",
    valor: "1500.00",
    dataPagamento: nowDate(),
    seuNumero: "PIX-00001",
    camara: "000",
    codFinalidadeTED: "",
    codFinalidadeDoc: "",
    codFinalidadeComp: "",
    tipoChavePix: "01",
    chavePix: "52998224725",
    txIdPix: "",
    logradouroFav: "RUA DAS FLORES",
    numeroFav: "123",
    bairroFav: "CENTRO",
    cidadeFav: "SAO PAULO",
    cepFav: "01001-000",
    estadoFav: "SP",
  },
  {
    ...defaultPagamento,
    bancoFavorecido: "237",
    agenciaFavorecido: "03290",
    dvAgenciaFav: "5",
    contaFavorecido: "000000012345",
    dvContaFav: "5",
    nomeFavorecido: "EMPRESA BETA SERVICOS LTDA",
    cpfCnpjFavorecido: "33.000.167/0001-01",
    tipoInscricaoFav: "2",
    valor: "8750.50",
    dataPagamento: nowDate(),
    seuNumero: "PIX-00002",
    camara: "000",
    codFinalidadeTED: "",
    codFinalidadeDoc: "",
    codFinalidadeComp: "",
    tipoChavePix: "02",
    chavePix: "financeiro@empresabeta.com.br",
    txIdPix: "",
    logradouroFav: "AV BRASIL",
    numeroFav: "500",
    bairroFav: "JARDIM AMERICA",
    cidadeFav: "RIO DE JANEIRO",
    cepFav: "20040-020",
    estadoFav: "RJ",
  },
];

// Compat
export const sampleLote = sampleLoteTED;
export const samplePagamentos = samplePagamentosTED;
